"use client";

import Link from "next/link";
import { ChevronRight, Activity, BarChart3, Database, Zap, ShieldCheck, GitBranch } from "lucide-react";
import { Navbar } from "../../components/Navbar";
import { Footer } from "../../components/Footer";
import { GlassPanel } from "../../components/ui/GlassPanel";
import { Reveal, Stagger, StaggerItem } from "../../components/motion";
import { DEMO_MODEL_METRICS, DEMO_FLEET_STATS } from "../../lib/demo-data";

function MetricBlock({ label, val, color }: { label: string; val: string; color: string }) {
  return (
    <div className="bg-cc-raised rounded-xl p-4 text-center">
      <div className="font-mono font-bold text-xl" style={{ color }}>{val}</div>
      <div className="text-cc-subtle text-[10px] font-mono tracking-widest uppercase mt-0.5">{label}</div>
    </div>
  );
}

function CodeBlock({ children }: { children: string }) {
  return (
    <pre className="bg-cc-surface-2 border border-cc-border rounded-xl px-4 py-3 text-[11px] font-mono text-cc-text leading-relaxed overflow-x-auto">
      {children}
    </pre>
  );
}

export default function AboutPage() {
  return (
    <div className="min-h-dvh bg-cc-bg text-cc-text flex flex-col">
      <Navbar />

      <div className="mt-[60px] border-b border-cc-border bg-cc-surface/60 backdrop-blur-sm">
        <div className="max-w-screen-xl mx-auto px-4 py-8">
          <Reveal>
            <div className="inline-block text-[10px] font-mono tracking-widest uppercase text-cc-muted border border-cc-border px-3 py-1 rounded-full mb-3">
              Methodology
            </div>
            <h1 className="font-display font-bold text-3xl text-cc-text mb-2">
              About YieldGuard
            </h1>
            <p className="text-cc-muted text-base max-w-xl">
              The engineering story behind the predictions — data, features, training, deployment.
            </p>
          </Reveal>
        </div>
      </div>

      <div className="flex-1 max-w-screen-xl mx-auto w-full px-4 py-8">
        <div className="max-w-3xl mx-auto space-y-14 pb-16">

          {/* ── What we built ──────────────────────────────────────────────── */}
          <section>
            <Reveal>
              <div className="flex items-center gap-2 mb-5">
                <Activity size={15} className="text-cc-healthy" />
                <h2 className="font-display font-bold text-cc-text text-xl">What we built</h2>
              </div>
              <div className="text-cc-muted text-sm leading-relaxed space-y-3">
                <p>
                  YieldGuard is an end-to-end predictive maintenance system that ingests sensor streams from industrial machines (PLCs, SCADA, IoT edge devices), engineers 256+ time-series features, and predicts equipment failure <strong className="text-cc-text">24 hours in advance</strong> with a calibrated probability score.
                </p>
                <p>
                  The system runs <strong className="text-cc-text">entirely in the browser</strong>. The LightGBM model is exported to a compact JSON format and scored via a TypeScript tree-walker — no API round-trips, no cold starts, no data leaving the user's device.
                </p>
              </div>
            </Reveal>
          </section>

          {/* ── Data ───────────────────────────────────────────────────────── */}
          <section>
            <Reveal>
              <div className="flex items-center gap-2 mb-5">
                <Database size={15} className="text-cc-healthy" />
                <h2 className="font-display font-bold text-cc-text text-xl">Training data</h2>
              </div>
              <div className="text-cc-muted text-sm leading-relaxed space-y-3 mb-4">
                <p>
                  Training data was generated by a physics-informed synthetic generator (`src/yieldguard/data/synthesizer.py`). 50 machines × 70 days × 10-minute intervals = <strong className="text-cc-text">504,000 rows</strong> across 6 sensor channels.
                </p>
                <p>
                  Each machine follows a physical signal model with per-channel degradation physics — exponential amplitude ramps for vibration/acoustic, temperature rise via bearing friction, RPM drift. Failure events are randomized (onset timing, magnitude, duration) to avoid a trivially separable dataset.
                </p>
              </div>
              <CodeBlock>{`Signal model:
  X(t) = μ_machine + seasonal(t) + degradation(t, t_fail) + noise(t)

Degradation onset:   ~48 hours before failure (randomized ±24h)
Magnitude factors:   vib ×2.5, temp ×1.8, aco ×2.2 (at peak)
Hard negatives:      5–8 recoverable excursions per machine
Label noise:         5% random flip on boundary samples
Positive class:      ~9.3% of total rows`}
              </CodeBlock>
            </Reveal>
          </section>

          {/* ── Feature engineering ────────────────────────────────────────── */}
          <section>
            <Reveal>
              <div className="flex items-center gap-2 mb-5">
                <BarChart3 size={15} className="text-cc-healthy" />
                <h2 className="font-display font-bold text-cc-text text-xl">Feature engineering</h2>
              </div>
              <div className="text-cc-muted text-sm leading-relaxed mb-4 space-y-3">
                <p>
                  <code className="font-mono text-cc-text">FeatureEngineer(TransformerMixin)</code> computes 256+ features per row. All temporal operations are performed inside <code className="font-mono text-cc-text">groupby('machine_id')</code> — never on a flat concatenated DataFrame — to prevent cross-machine data leakage.
                </p>
                <p>
                  The engineer is <strong className="text-cc-text">joblib-serialized alongside the model</strong> at training time and loaded together at inference. This guarantees the exact same feature computation between training and serving.
                </p>
              </div>
              <CodeBlock>{`Rolling stats × 4 windows [6, 12, 36, 144] samples
  → mean, std, range, skew, kurt             (30 per channel = 180)

EWMA × 2 spans [12, 72] + deviation          (4 per channel  = 24)

Lag + diff + pct_change × 4 lags             (12 per channel = 72)
  pct_change clipped to [-10, 10] (avoids ±∞ at near-zero)

Rate of change (raw + smoothed)              (2 per channel  = 12)

FFT: energy, dominant_hz, spectral_entropy   (3 per channel  = 18)

Cross-channel:
  vibration × temperature coupling
  current draw relative to RPM (power proxy)
  pressure / temperature ratio               (4 features)
                                         ───────────────
                                         Total: 310 → curated to 256`}
              </CodeBlock>
            </Reveal>
          </section>

          {/* ── Training ───────────────────────────────────────────────────── */}
          <section>
            <Reveal>
              <div className="flex items-center gap-2 mb-5">
                <GitBranch size={15} className="text-cc-healthy" />
                <h2 className="font-display font-bold text-cc-text text-xl">Training methodology</h2>
              </div>
              <div className="text-cc-muted text-sm leading-relaxed space-y-3 mb-4">
                <p>
                  Cross-validation uses <code className="font-mono text-cc-text">TimeSeriesExpandingCV</code> with a <strong className="text-cc-text">24-hour gap</strong> between train and validation folds. The gap prevents the model from seeing the run-up to a failure event in both sets simultaneously.
                </p>
                <p>
                  Class imbalance (~9% positive) is handled via <code className="font-mono text-cc-text">scale_pos_weight ≈ 9.8</code> — no oversampling or SMOTE. The primary metric is <strong className="text-cc-text">PR-AUC</strong> (average precision), which is more informative than ROC-AUC for imbalanced data.
                </p>
                <p>
                  Optuna TPE Bayesian HPO runs 50 trials per model, maximizing PR-AUC across folds. The final model is refit on all training data using the <strong className="text-cc-text">median best_iteration</strong> across folds (rather than allowing early stopping on a combined dataset, which would cause overfitting).
                </p>
                <p>
                  Probabilities are <strong className="text-cc-text">isotonic calibrated</strong> on a held-out fold — the model's raw sigmoid output is a ranking score, not a probability; calibration makes the output honest.
                </p>
              </div>
              <CodeBlock>{`Strategy:    TimeSeriesExpandingCV — 5 folds, 24h gap
Objective:   PR-AUC (primary), ROC-AUC (secondary)
Imbalance:   scale_pos_weight = n_neg / n_pos ≈ 9.8
HPO:         Optuna TPE, 50 trials, pruning enabled
Refit:       n_estimators = median(best_iteration_ across folds)
Calibration: IsotonicRegression on held-out fold`}
              </CodeBlock>
            </Reveal>
          </section>

          {/* ── Model metrics ──────────────────────────────────────────────── */}
          <section>
            <Reveal>
              <div className="flex items-center gap-2 mb-5">
                <Zap size={15} className="text-cc-healthy" />
                <h2 className="font-display font-bold text-cc-text text-xl">Model performance</h2>
              </div>
              <div className="text-cc-muted text-sm leading-relaxed mb-5">
                Evaluated on a time-series holdout (last 20% of the data, never seen during training or HPO). All metrics shown at the tuned operating threshold.
              </div>
              <div className="grid grid-cols-2 gap-4 mb-5">
                {(["lightgbm", "xgboost"] as const).map(m => {
                  const met = DEMO_MODEL_METRICS[m];
                  const color = m === "lightgbm" ? "#2DD4BF" : "#6366F1";
                  return (
                    <GlassPanel key={m} padding="p-4">
                      <div className="flex items-center gap-2 mb-3">
                        <span className="w-2 h-2 rounded-full" style={{ background: color }} />
                        <span className="font-display font-semibold text-cc-text text-sm">
                          {m === "lightgbm" ? "LightGBM" : "XGBoost"}
                        </span>
                      </div>
                      <div className="grid grid-cols-2 gap-2">
                        {[
                          { label: "PR-AUC",    val: met.prAuc.toFixed(4) },
                          { label: "ROC-AUC",   val: met.rocAuc.toFixed(4) },
                          { label: "Threshold",  val: met.threshold.toFixed(3) },
                          { label: "Trees",      val: String(met.trees) },
                        ].map(s => (
                          <div key={s.label} className="bg-cc-raised rounded-lg p-2 text-center">
                            <div className="font-mono font-semibold text-sm" style={{ color }}>{s.val}</div>
                            <div className="text-[9px] text-cc-subtle font-mono uppercase tracking-wider">{s.label}</div>
                          </div>
                        ))}
                      </div>
                    </GlassPanel>
                  );
                })}
              </div>

              <div className="text-cc-subtle text-xs font-mono">
                These metrics reflect the synthetic validation set. Real-world performance on your specific machine class will vary — we recommend fine-tuning on historical failure data for production use.
              </div>
            </Reveal>
          </section>

          {/* ── In-browser engine ──────────────────────────────────────────── */}
          <section>
            <Reveal>
              <div className="flex items-center gap-2 mb-5">
                <ShieldCheck size={15} className="text-cc-healthy" />
                <h2 className="font-display font-bold text-cc-text text-xl">In-browser inference</h2>
              </div>
              <div className="text-cc-muted text-sm leading-relaxed space-y-3 mb-4">
                <p>
                  The trained LightGBM model is exported via <code className="font-mono text-cc-text">booster_.dump_model()</code> to a compact JSON structure and served as a static file. A TypeScript tree-walker (<code className="font-mono text-cc-text">web/lib/engine/model.ts</code>) scores the ensemble by recursively walking split nodes, summing leaf values, applying sigmoid, then isotonic calibration.
                </p>
                <p>
                  The feature pipeline (<code className="font-mono text-cc-text">web/lib/engine/features.ts</code>) is a port of the Python <code className="font-mono text-cc-text">FeatureEngineer</code> — rolling statistics, EWMA, lag/diff/pct (clipped), ROC, and a direct DFT (FFT without scipy) for spectral features.
                </p>
              </div>
              <CodeBlock>{`Export:    lgb_model.booster_.dump_model() → model.json (~800 KB)
           isotonic calibration params → calibration_x/y arrays
           feature names + healthy baseline stats → feature_spec.json
           5 demo machine series → demo_scenarios.json

TS scorer: O(n × depth) per tree — ~1000 trees × depth 6
           Total inference: <50ms on modern hardware
           No WASM, no server, no API — pure TypeScript`}
              </CodeBlock>
            </Reveal>
          </section>

          {/* ── Tech stack ─────────────────────────────────────────────────── */}
          <section>
            <Reveal>
              <div className="flex items-center gap-2 mb-5">
                <Database size={15} className="text-cc-healthy" />
                <h2 className="font-display font-bold text-cc-text text-xl">Tech stack</h2>
              </div>
              <Stagger className="grid grid-cols-2 gap-3" staggerDelay={0.04}>
                {[
                  { category: "ML / Python",   items: ["XGBoost", "LightGBM", "scikit-learn", "Optuna", "SHAP", "NumPy", "Pandas", "SciPy"] },
                  { category: "Serving",        items: ["FastAPI", "Pydantic v2", "joblib", "uvicorn", "Docker", "Render"] },
                  { category: "Frontend",       items: ["Next.js 15", "TypeScript", "Tailwind CSS", "framer-motion", "Recharts", "lucide-react"] },
                  { category: "In-browser ML",  items: ["LightGBM JSON export", "TypeScript tree scorer", "Direct DFT (FFT)", "Isotonic calibration"] },
                ].map(group => (
                  <StaggerItem key={group.category}>
                    <GlassPanel padding="p-4">
                      <div className="text-[10px] font-mono tracking-widest uppercase text-cc-muted mb-2">{group.category}</div>
                      <div className="flex flex-wrap gap-1.5">
                        {group.items.map(item => (
                          <span key={item} className="text-[10px] font-mono text-cc-muted border border-cc-border/60 px-1.5 py-0.5 rounded-md">
                            {item}
                          </span>
                        ))}
                      </div>
                    </GlassPanel>
                  </StaggerItem>
                ))}
              </Stagger>
            </Reveal>
          </section>

          {/* ── Architecture ───────────────────────────────────────────────── */}
          <section>
            <Reveal>
              <div className="flex items-center gap-2 mb-5">
                <GitBranch size={15} className="text-cc-healthy" />
                <h2 className="font-display font-bold text-cc-text text-xl">Architecture</h2>
              </div>
              <CodeBlock>{`Browser (Next.js on Vercel)
  Demo page ──┐
  Dashboard ──┼──► web/lib/engine/
              │     features.ts  — 256+ feature computation
              │     model.ts     — LightGBM tree scorer + calibration
              │     explain.ts   — risk driver ranking
              │     predict.ts   — orchestration
              │       ▲ reads static JSON artifacts (no API)
              │
              └ web/lib/engine/
                  model.json          — LightGBM dump_model() export
                  feature_spec.json   — feature metadata + baselines
                  demo_scenarios.json — 5 sample machine histories

Python (offline training — source of truth)
  synthesizer.py    — physics-informed synthetic data
  preprocessor.py   — cleaning, imputation, stuck sensor detection
  engineer.py       — FeatureEngineer(TransformerMixin) → 256 features
  trainer.py        — CV + Optuna HPO + calibration
  export_model.py   — writes engine JSON artifacts

FastAPI (Render — optional, not on critical path)
  POST /predict → PerMachineBuffer(288) → features → model → response
  POST /explain → SHAP TreeExplainer (on demand)
  GET  /drift   → PSI + KS drift report`}
              </CodeBlock>
            </Reveal>
          </section>

          {/* ── Links ──────────────────────────────────────────────────────── */}
          <Reveal>
            <GlassPanel padding="p-5">
              <div className="flex flex-wrap gap-4 text-sm">
                <Link href="/guide" className="flex items-center gap-1 text-cc-healthy font-mono hover:gap-1.5 transition-all text-xs">
                  User guide <ChevronRight size={11} />
                </Link>
                <Link href="/demo" className="flex items-center gap-1 text-cc-muted font-mono hover:text-cc-text hover:gap-1.5 transition-all text-xs">
                  Interactive demo <ChevronRight size={11} />
                </Link>
                <Link href="/dashboard" className="flex items-center gap-1 text-cc-muted font-mono hover:text-cc-text hover:gap-1.5 transition-all text-xs">
                  Analyze your data <ChevronRight size={11} />
                </Link>
                <a
                  href="https://github.com/AyushCoder9/YieldGuard"
                  target="_blank" rel="noopener noreferrer"
                  className="flex items-center gap-1 text-cc-muted font-mono hover:text-cc-text hover:gap-1.5 transition-all text-xs"
                >
                  Source code <ChevronRight size={11} />
                </a>
              </div>
            </GlassPanel>
          </Reveal>
        </div>
      </div>

      <Footer />
    </div>
  );
}
